name: CI - MLflow Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy dagshub

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/saktyahari2004/Eksperimen_SML_Dwi_Saktya_Hari_Aditya.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=saktyahari2004" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local --experiment-name="Titanic-Classification-CI"

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(python -c "
          import mlflow, os
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          client = mlflow.tracking.MlflowClient()
          exp = client.get_experiment_by_name('Titanic-Classification-CI')
          runs = client.search_runs(exp.experiment_id, order_by=['start_time DESC'], max_results=1)
          print(runs[0].info.run_id)
          ")
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Latest run_id: $RUN_ID"

      - name: Install Python dependencies for artifact download
        run: pip install mlflow==2.19.0

      - name: Download MLflow artifacts
        run: |
          mkdir -p /tmp/mlflow_artifacts
          python -c "
          import mlflow, os
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          client = mlflow.tracking.MlflowClient()
          run_id = '${{ steps.get_run_id.outputs.run_id }}'
          client.download_artifacts(run_id, 'model', '/tmp/mlflow_artifacts')
          print('Artifacts downloaded!')
          "

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-model-artifacts
          path: /tmp/mlflow_artifacts/

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" \
            --name titanic-model \
            --env-manager=local

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag titanic-model ${{ secrets.DOCKER_USERNAME }}/titanic-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/titanic-model:latest
