name: CI - MLflow Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy dagshub

      - name: Set MLflow Tracking URI
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/saktyahari2004/Eksperimen_SML_Dwi_Saktya_Hari_Aditya.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=saktyahari2004" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}" >> $GITHUB_ENV

      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          pip install mlflow
          python -c "
          import mlflow, os
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          client = mlflow.tracking.MlflowClient()
          exp = client.get_experiment_by_name('Titanic-Classification-CI')
          runs = client.search_runs(exp.experiment_id, order_by=['start_time DESC'], max_results=1)
          print('Latest run_id:', runs[0].info.run_id)
          "

      - name: Install Python dependencies for upload
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Upload to Google Drive
        uses: adityakumar2809/google-drive-upload@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: 'MLProject'
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}

      - name: Build Docker Model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$(python -c "
          import mlflow, os
          mlflow.set_tracking_uri(os.environ['MLFLOW_TRACKING_URI'])
          client = mlflow.tracking.MlflowClient()
          exp = client.get_experiment_by_name('Titanic-Classification-CI')
          runs = client.search_runs(exp.experiment_id, order_by=['start_time DESC'], max_results=1)
          print(runs[0].info.run_id)
          ")/model" \
            --name titanic-model

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag titanic-model ${{ secrets.DOCKER_USERNAME }}/titanic-model:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/titanic-model:latest
